# Generated by Django 4.2.4 on 2023-08-14 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4)),
                ('bloger_email', models.EmailField(default='@EmailField', max_length=100, unique=True)),
                ('contact_info', models.CharField(blank=True, max_length=250, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='username_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
