# Generated by Django 4.2.4 on 2023-08-14 11:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=100, verbose_name='blog_name')),
                ('blog_image', models.ImageField(upload_to='blog_images/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('blog_categery', models.CharField(choices=[('Science', 'Science'), ('Business', 'Business'), ('Personal', 'Personal'), ('World', 'World'), ('Opinion', 'Opinion'), ('Techno', 'Techno'), ('Money', 'Money'), ('Politics', 'Politics'), ('Design', 'Design'), ('Travel', 'Travel'), ('Style', 'Style'), ('Culture', 'Culture'), ('Health', 'Health')], max_length=10)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloger_set', to='users.bloger')),
            ],
        ),
    ]
