# Generated by Django 4.2.6 on 2023-11-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_blog',
            name='blog_categery',
            field=models.CharField(choices=[('Culture', 'Culture'), ('Style', 'Style'), ('Science', 'Science'), ('Travel', 'Travel'), ('Design', 'Design'), ('Health', 'Health'), ('Politics', 'Politics'), ('World', 'World'), ('Techno', 'Techno'), ('Personal', 'Personal'), ('Opinion', 'Opinion'), ('Business', 'Business'), ('Money', 'Money')], max_length=10),
        ),
    ]
