# Generated by Django 4.2.7 on 2023-11-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_page', '0002_alter_create_blog_blog_categery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_blog',
            name='blog_categery',
            field=models.CharField(choices=[('Health', 'Health'), ('Techno', 'Techno'), ('Money', 'Money'), ('Design', 'Design'), ('Science', 'Science'), ('Style', 'Style'), ('Business', 'Business'), ('World', 'World'), ('Politics', 'Politics'), ('Culture', 'Culture'), ('Personal', 'Personal'), ('Travel', 'Travel'), ('Opinion', 'Opinion')], max_length=10),
        ),
    ]
